## Analisis de actividad de usuarios

### Raw data 
whit the help of pandas now the *"product_activity.csv"* is now ready to be manipulated and transform in data that we can use to do our own metrics

In [2]:
import pandas as pd

# read the data set:
raw_data_df = pd.read_csv("product_activity.csv")

# show the first 5 rows
display(raw_data_df.head())

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type
0,U01988,2025-02-18T02:07:44,PY,pro,26.0,P0008515,sport,2025-05-07T20:55:28,7,16,78,mobile
1,U00236,2025-06-22T07:49:10,BR,free,27.0,P0001023,tech,2025-09-13T20:31:06,1,9,83,web
2,U00791,2024-02-12T02:45:45,CL,free,28.0,P0003405,tech,2024-02-14T05:17:48,11,2,2,mobile
3,U01522,2024-09-22T07:06:50,US,free,16.0,P0006524,finance,2024-09-24T07:51:34,5,2,2,web
4,U01092,2025-07-18T02:27:52,PY,free,NaN,P0004665,education,2025-07-24T04:56:56,7,2,6,mobile

### Initial analysis

In [31]:
# initial information of the df
raw_data_description = pd.DataFrame(raw_data_df.describe(include="all"))
display(raw_data_description)

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type
count,8782,8782,8782,8782,8028.000000,8782,8782,8782,8782.000000,8782.000000,8782.000000,8782
unique,2010,2010,10,19,NaN,8610,53,8609,NaN,NaN,NaN,6
top,U00087,2024-01-08T12:18:18,US,free,NaN,P0002865,tech,2024-02-14T15:55:59,NaN,NaN,NaN,web
freq,40,40,1928,5978,NaN,2,1187,3,NaN,NaN,NaN,4416
mean,NaN,NaN,NaN,NaN,27.902591,NaN,NaN,NaN,6.918356,8.324186,29.479390,NaN
std,NaN,NaN,NaN,NaN,7.547052,NaN,NaN,NaN,5.127311,6.754906,36.819928,NaN
min,NaN,NaN,NaN,NaN,16.000000,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,22.000000,NaN,NaN,NaN,3.000000,4.000000,5.000000,NaN
50%,NaN,NaN,NaN,NaN,28.000000,NaN,NaN,NaN,6.000000,6.000000,17.000000,NaN
75%,NaN,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,9.000000,11.000000,40.000000,NaN
max,NaN,NaN,NaN,NaN,58.000000,NaN,NaN,NaN,74.000000,39.000000,404.000000,NaN

### description
One can see that at first everything seems normal, but already here we can see that days_since_signup, created_at, post_created_at have the wrong format, they are not datetime